# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SandBoxApp' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SandBoxApp

  

  platform :ios, '9.0'
  target 'SandBoxAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SandBoxApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SandBoxApp-tvOS

  target 'SandBoxApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
